apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: pptx-api
  name: pptx-api
  namespace: oc-sandbox
spec:
  failedBuildsHistoryLimit: 1
  successfulBuildsHistoryLimit: 1
  output:
    to:
      kind: ImageStreamTag
      name: pptx-api:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: dotnet:6.0
        namespace: openshift
    type: Source
